language: rust

rust:
  - stable
  - beta
  - nightly
  
env:
  - FLAGS="--no-default-features"
  - FLAGS="--features std"
  - FLAGS="--no-default-features --features num"
  - FLAGS="--features std --features num"

script: cargo test $FLAGS
